# ===== QUICK START - NO INSTALLATION NEEDED =====
# Just run this to get started immediately!

message("Loading glycofragR...\n")
source('load_glycofragr.R')

message("\n✓ glycofragR is ready to use!\n")

message("Example usage:")
message("====================================================")
message("")
message("library(reticulate)")
message("library(writexl)")  
message("")
message("# Create analysis")
message("analysis <- glycan_analysis_new('4502', 'permethylated_reduced')")
message("")
message("# Get data as native R data.frames")
message("theoretical <- glycan_analysis_theoretical_df(analysis)")
message("clean <- glycan_analysis_clean_df(analysis)")
message("summary <- glycan_analysis_summary(analysis)")
message("")
message("# Use with R functions")
message("head(clean)")
message("nrow(clean)")
message("")
message("# Export to Excel")
message("write_xlsx(")
message("  list(clean = clean, summary = summary),")
message("  path = 'results.xlsx'")
message(")")
message("")
message("====================================================")
message("")
message("For more examples, see:")
message("  - QUICK_REFERENCE.md")
message("  - R_WRAPPER_USAGE_UPDATE.md")
message("  - GlycofragR_test_UPDATED.R")
